security:
 oauth2:
   client:
    client-id: 7014caa7d424dbdaf508
    client-Secret: bfc0f356d0b76ae4767f01d5045ab720cf3b1205
    access-token-uri: https://github.com/login/oauth/access_token
    user-authorization-uri: https://github.com/login/oauth/authorize
    client-authentication-scheme: form
   resource:
    user-info-uri: https://api.github.com/user
    prefer-token-info: false
    